# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-10 02:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_UUID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=500)),
                ('startTimestamp', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('uidType', models.IntegerField(default=1)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Student_Info')),
            ],
        ),
        migrations.AlterField(
            model_name='instructor_info',
            name='username',
            field=models.CharField(max_length=200),
        ),
    ]
