# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-10 02:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20160710_0204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructor_course',
            old_name='student',
            new_name='instructor',
        ),
    ]
