# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-15 02:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20160710_0215'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course_topics',
            options={'ordering': ['topicName']},
        ),
    ]
