# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-19 06:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20160715_0245'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor_UUID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=500)),
                ('startTimestamp', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('uidType', models.IntegerField(default=1)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Instructor_Info')),
            ],
        ),
    ]
