# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-09 03:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_instructor_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Login_Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=200)),
                ('startTimestamp', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('endTimestamp', models.DateTimeField(blank=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Student_Info')),
            ],
        ),
    ]
