# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-09 03:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_student_login_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_login_log',
            name='endTimestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
