# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-10 22:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0003_auto_20160710_0215'),
    ]

    operations = [
        migrations.CreateModel(
            name='MCQ_Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('topicTag', models.CharField(default='', max_length=200)),
                ('choiceA', models.CharField(default='', max_length=1000)),
                ('choiceB', models.CharField(default='', max_length=1000)),
                ('choiceC', models.CharField(default='', max_length=1000)),
                ('choiceD', models.CharField(default='', max_length=1000)),
                ('choiceE', models.CharField(default='', max_length=1000)),
                ('choiceF', models.CharField(default='', max_length=1000)),
                ('numChoices', models.IntegerField(default=4)),
                ('answer', models.CharField(max_length=10)),
                ('level', models.CharField(default='Easy', max_length=10)),
                ('datetime', models.DateField()),
                ('sentFlag', models.BooleanField(default=False)),
                ('totStudents', models.IntegerField(default=0)),
                ('totAnswers', models.IntegerField(default=0)),
                ('totCorrectAnswers', models.IntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Course')),
            ],
            options={
                'ordering': ['datetime'],
            },
        ),
        migrations.CreateModel(
            name='Recommendations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('fileName', models.CharField(default='path', max_length=200)),
                ('rank', models.IntegerField(default=0)),
                ('upVotes', models.IntegerField(default=0)),
                ('downVotes', models.IntegerField(default=0)),
                ('totalVotes', models.IntegerField(default=0)),
                ('averageRatings', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructor.MCQ_Question')),
            ],
        ),
    ]
