# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-11 15:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0003_auto_20160710_0215'),
        ('instructor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selAnswer', models.CharField(max_length=200)),
                ('correctFlag', models.IntegerField(default=0)),
                ('recFlag', models.IntegerField(default=0)),
                ('rec1', models.IntegerField(default=0)),
                ('rec2', models.IntegerField(default=0)),
                ('rec3', models.IntegerField(default=0)),
                ('rec4', models.IntegerField(default=0)),
                ('rec5', models.IntegerField(default=0)),
                ('bestRec', models.IntegerField(default=0)),
                ('rec1Vote', models.IntegerField(default=0)),
                ('rec2Vote', models.IntegerField(default=0)),
                ('rec3Vote', models.IntegerField(default=0)),
                ('rec4Vote', models.IntegerField(default=0)),
                ('rec5Vote', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructor.MCQ_Question')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Student_Info')),
            ],
        ),
        migrations.CreateModel(
            name='Student_Marks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numQues', models.IntegerField(default=0)),
                ('numEasyQues', models.IntegerField(default=0)),
                ('numModerateQues', models.IntegerField(default=0)),
                ('numHardQues', models.IntegerField(default=0)),
                ('numCorrAns', models.IntegerField(default=0)),
                ('numEasyCorrAns', models.IntegerField(default=0)),
                ('numModerateCorrAns', models.IntegerField(default=0)),
                ('numHardCorrAns', models.IntegerField(default=0)),
                ('totMarks', models.IntegerField(default=0)),
                ('marks', models.IntegerField(default=0)),
                ('bonus', models.IntegerField(default=0)),
                ('currStreak', models.IntegerField(default=0)),
                ('streak05', models.IntegerField(default=0)),
                ('streak10', models.IntegerField(default=0)),
                ('streak20', models.IntegerField(default=0)),
                ('rank', models.IntegerField(default=0)),
                ('badge', models.CharField(max_length=200)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Student_Info')),
            ],
        ),
    ]
