# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-11 23:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_answers',
            name='bestRec',
        ),
        migrations.RemoveField(
            model_name='student_answers',
            name='rec1',
        ),
        migrations.RemoveField(
            model_name='student_answers',
            name='rec1Vote',
        ),
        migrations.RemoveField(
            model_name='student_answers',
            name='rec2',
        ),
        migrations.RemoveField(
            model_name='student_answers',
            name='rec2Vote',
        ),
        migrations.RemoveField(
            model_name='student_answers',
            name='rec3',
        ),
        migrations.RemoveField(
            model_name='student_answers',
            name='rec3Vote',
        ),
        migrations.RemoveField(
            model_name='student_answers',
            name='rec4',
        ),
        migrations.RemoveField(
            model_name='student_answers',
            name='rec4Vote',
        ),
        migrations.RemoveField(
            model_name='student_answers',
            name='rec5',
        ),
        migrations.RemoveField(
            model_name='student_answers',
            name='rec5Vote',
        ),
    ]
