# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-11 23:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0001_initial'),
        ('account', '0003_auto_20160710_0215'),
        ('student', '0002_auto_20160711_2303'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Recommendations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voteFlag', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructor.MCQ_Question')),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructor.Recommendations')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Student_Info')),
            ],
        ),
    ]
