# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-12 23:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_student_recommendations'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_answers',
            name='numAttemps',
            field=models.IntegerField(default=1),
        ),
    ]
