# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-14 01:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_student_answers_numattemps'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_answers',
            name='answerSequence',
            field=models.CharField(default='X|', max_length=500),
        ),
    ]
