# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-14 01:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_student_answers_answersequence'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_answers',
            old_name='numAttemps',
            new_name='numAttempts',
        ),
    ]
