# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-14 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20160714_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_answers',
            name='answerSequence',
            field=models.CharField(default='X', max_length=500),
        ),
    ]
