# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-20 03:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20160715_0245'),
        ('instructor', '0002_auto_20160715_1919'),
        ('student', '0007_auto_20160714_0218'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Explanations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explanationText', models.CharField(default='', max_length=1000)),
                ('score', models.IntegerField(default=0)),
                ('upvotes', models.IntegerField(default=0)),
                ('downvotes', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructor.MCQ_Question')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Student_Info')),
            ],
        ),
    ]
