# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-20 04:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_student_explanations'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_explanations',
            name='postTimeStamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
