# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-27 02:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_student_explanations_posttimestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_answers',
            name='numCorrectAttempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student_answers',
            name='numAttempts',
            field=models.IntegerField(default=0),
        ),
    ]
