# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-17 22:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20160715_0245'),
        ('instructor', '0002_auto_20160715_1919'),
        ('student', '0010_auto_20160727_0223'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Answers_ActivityLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(default='', max_length=1000)),
                ('answerFlag', models.IntegerField(default=0)),
                ('activityTimeStamp', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructor.MCQ_Question')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Student_Info')),
            ],
        ),
        migrations.AlterField(
            model_name='student_answers',
            name='answerSequence',
            field=models.CharField(max_length=500),
        ),
    ]
