# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-09 03:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_student_login_log'),
        ('instructor', '0002_auto_20160715_1919'),
        ('student', '0011_auto_20160817_2246'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Answer_Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=200)),
                ('activityTimestamp', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Course')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructor.MCQ_Question')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Student_Info')),
            ],
        ),
    ]
