# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-01 02:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0003_auto_20161031_2134'),
        ('account', '0007_auto_20160909_0330'),
        ('student', '0013_auto_20160909_0442'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard_Activity_Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blur_type', models.IntegerField(default=0)),
                ('dashboard_timestamp', models.DateTimeField(blank=True)),
                ('dashboard_time', models.BigIntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Student_Info')),
            ],
        ),
        migrations.CreateModel(
            name='Student_Activity_Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.IntegerField(default=0)),
                ('blur_type', models.IntegerField(default=0)),
                ('retry_timestamp', models.DateTimeField(blank=True)),
                ('review_timestamp', models.DateTimeField(blank=True)),
                ('today_quiz_timestamp', models.DateTimeField(blank=True)),
                ('question_list_timestamp', models.DateTimeField(blank=True)),
                ('retry_time', models.BigIntegerField(default=0)),
                ('review_time', models.BigIntegerField(default=0)),
                ('today_quiz_time', models.BigIntegerField(default=0)),
                ('question_list_time', models.BigIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructor.MCQ_Question')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Student_Info')),
            ],
        ),
    ]
