# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-01 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_dashboard_activity_log_student_activity_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard_activity_log',
            name='browser',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student_activity_log',
            name='browser',
            field=models.IntegerField(default=0),
        ),
    ]
