# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-01 12:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0016_auto_20170401_0938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dashboard_activity_log',
            old_name='dashboard_time',
            new_name='time',
        ),
        migrations.RenameField(
            model_name='dashboard_activity_log',
            old_name='dashboard_timestamp',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='student_activity_log',
            old_name='retry_time',
            new_name='time',
        ),
        migrations.RenameField(
            model_name='student_activity_log',
            old_name='retry_timestamp',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='dashboard_activity_log',
            name='question_list_time',
        ),
        migrations.RemoveField(
            model_name='dashboard_activity_log',
            name='question_list_timestamp',
        ),
        migrations.RemoveField(
            model_name='student_activity_log',
            name='review_time',
        ),
        migrations.RemoveField(
            model_name='student_activity_log',
            name='review_timestamp',
        ),
        migrations.RemoveField(
            model_name='student_activity_log',
            name='today_quiz_time',
        ),
        migrations.RemoveField(
            model_name='student_activity_log',
            name='today_quiz_timestamp',
        ),
    ]
