# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-10 05:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0003_auto_20161031_2134'),
        ('account', '0007_auto_20160909_0330'),
        ('student', '0018_auto_20170401_1215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Explanation_Scroll_Activity_Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.IntegerField(default=0)),
                ('blur_type', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(blank=True)),
                ('scroll', models.BigIntegerField(default=0)),
                ('browser', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructor.MCQ_Question')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Student_Info')),
            ],
        ),
    ]
