# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-10 08:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0003_auto_20161031_2134'),
        ('account', '0007_auto_20160909_0330'),
        ('student', '0019_explanation_scroll_activity_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Activity_Log_WithScroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.IntegerField(default=0)),
                ('blur_type', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(blank=True)),
                ('time', models.BigIntegerField(default=0)),
                ('browser', models.IntegerField(default=0)),
                ('scrollTimestamp', models.DateTimeField(blank=True)),
                ('scrollPoints1', models.BigIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_2', to='instructor.MCQ_Question')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_1', to='account.Student_Info')),
            ],
        ),
        migrations.RemoveField(
            model_name='explanation_scroll_activity_log',
            name='question',
        ),
        migrations.RemoveField(
            model_name='explanation_scroll_activity_log',
            name='student',
        ),
        migrations.RemoveField(
            model_name='student_activity_log',
            name='question',
        ),
        migrations.RemoveField(
            model_name='student_activity_log',
            name='student',
        ),
        migrations.DeleteModel(
            name='Explanation_Scroll_Activity_Log',
        ),
        migrations.DeleteModel(
            name='Student_Activity_Log',
        ),
    ]
