# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-21 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=256)),
                ('body', models.TextField(max_length=500)),
                ('likes', models.IntegerField()),
            ],
        ),
    ]
