# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-21 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
